### ISSUE TITLE
i would like to use the npm package

### ISSUE THREAD

**Issue by swyxio** [swyxio/babel-plugin-react-hooks#1]
hey! are you using the babel-plugin-react-hooks namespace? i'd love to use it if you aren't.

**Comment by lttb** [comment]
hi @sw-yx! at first, I wanted to publish some experiments with the kind of optimizations for the react hooks like `useEffect`, `useCallback` and so on, for auto-filling the second (memo keys) argument with the context analysis by babel

and maybe later collect here some other `babel-plugins` that might help to work with the hooks

**Comment by swyxio** [comment]
ah. ok then.
